language: python
python:
  - "3.8"
  - "3.7"
install:
  - pip install -e .[dev]
script:
  - black redbrick --check
#   - pylint redbrick
#   - pydocstyle redbrick
#   - pycodestyle redbrick
#   - mypy redbrick --strict
deploy:
  provider: pypi
  username: __token__
  password:
    secure: ${PYPI}
  on:
    tags: false
    branch: master
  distributions: "bdist_wheel sdist"
